theme: jekyll-theme-slate

title: kenmoritest's page
description: KenmoriTest's test page to learn github page.
show_downloads: false

url:              http://dev-sec.io
baseurl:          /blog

menu:
  - title:        Blog
    url:          /blog

  - title:        Home
    url:          /
